[introduccion]
Titulo = ["FCFS", "Memoria No Continua", "Memoria No Reubicable"]
Autor = ["Jorge Ruiz", "Ivan Ruiz"]

[mensajes]
error = "☒ Ha ocurrido un error ☒"
acierto = "☑ Todo correcto ☑"
advertencia = "⚠ Hay algún problema, resumiendo ⚠"

[archivos]
archivoSalida = "res.log" # Abrir con el comando cat en la terminal para correcta muestra
archivoEntrada = "data.csv" # No cambiar si no se cambia el nombre del archivo o rellenar nuevo archivo con mismo formato
