[introduccion]
Titulo = ["FCFS", "Memoria No Continua", "Memoria No Reubicable", "Sistemas Operativos", "2019-2020"]
Autor = ["Jorge Ruiz", "Ivan Ruiz"]

[mensajes]
errorGeneral = "☒ Ha ocurrido un error, saliendo de la rama actual ☒"
aciertoGeneral = "☑ Todo correcto, continuando ☑"
advertenciaGeneral = "⚠ Hay algún problema, resumiendo ejecucion ⚠"

[archivos]
archivoSalida = "res.log" # Abrir con el comando cat en la terminal para correcta muestra
archivoEntrada = "data.csv" # No cambiar si no se cambia el nombre del archivo o rellenar nuevo archivo con mismo formato
