[introduccion]
Titulo = ["FCFS", "Memoria No Continua", "Memoria No Reubicable", "Sistemas Operativos", "2019-2020"]
Autor = ["Jorge Ruiz", "Ivan Ruiz"]

[mensajes]
errorGeneral = "☒ Si ves un mensaje como este, es que has introducido mal los datos o hay un problema ☒"
mensajeAlgoritmo = "☑ Ejecutando algoritmo | FCFS-SN-NN ☑"
advertenciaGeneral = "⚠ Si tiene algún problema con el algoritmo, vea la opción de ayuda en el menú inferior ⚠"

[archivos]
archivoSalida = "res.log" # Abrir con el comando cat en la terminal para correcta muestra
archivoEntrada = "data.csv" # No cambiar si no se cambia el nombre del archivo o rellenar nuevo archivo con mismo formato
