[introduccion]
Titulo = ["FCFS", "Memoria No Continua", "Memoria No Reubicable"]
Autor = ["Autor: Iván Ruiz"]
Asignatura = ["Sistemas Operativos", "2019-2020"]

[mensajes]
errorGeneral = "☒ Si ves un mensaje como este, es que hasintroducido mal los datos o hay un problema ☒"
mensajeAlgoritmo = "☑ Ejecutando algoritmo | FCFS-SN-NN ☑"
advertenciaGeneral = "⚠ Esto no es un error, si ves este cuadro estás recibiendo un aviso, todo normal ⚠"

[archivos]
archivoSalida = "Log/res.log" # Abrir con el programa para una correcta muestra
archivoEntrada = "Data/data.csv" # No cambiar si no se cambia el nombre del archivo o rellenar nuevo archivo con mismo formato
