[introduccion]
Titulo = ["FCFS", "Memoria No Continua", "Memoria No Reubicable"]
Autor = ["Autor: Iván Ruiz"]
Asignatura = ["Sistemas Operativos", "2019-2020"]

[mensajes]
errorGeneral = "☒ Esto es un error ☒"
mensajeAlgoritmo = "☑ Ejecutando algoritmo | FCFS-SN-NCNR ☑"
advertenciaGeneral = "⚠ Esto es solo un aviso ⚠"

[archivos]
archivoSalida = "Log/res.log" # Abrir con el programa para una correcta muestra
archivoSalidaBN = "Log/res_bn.log"
archivoEntrada = "Data/data.csv" # Crear archivo antes
